isooproject:
  name: Leesoo YAML
---
#아무 설정도 안했기 때문에 디폴트로 뜬다.
spring:
  profiles: default
isooproject:
  name: Leesoo Default
  pojoList:
  - name: my name
    description: my description
  - name: another name
    description: another description
  work-for: Microsoft
  whereToGo: Seattle
  foo_bar: baz
  time1: 1000
  time2: PT10H
  time3: 10s
---
spring:
  profiles: prod
isooproject:
  name: Leesoo Prod
  pojoList:
  - name: my name
    description: my description
  - name: another name
    description: another description
  - name: another name
    description: another description
  work-for: Microsoft
  whereToGo: Seattle
  foo_bar: baz
  time1: 2000
  time2: PT10H
  time3: 20s
---
spring:
  profiles: dev
isooproject:
  name: Leesoo Dev
  pojoList:
  - name: my name
    description: my description
  work-for: Microsoft
  whereToGo: Seattle
  foo_bar: baz
  time1: 3000
  time2: PT10H
  time3: 30s

