#아무 설정도 안했기 때문에 디폴트로 뜬다.
spring:
  profiles: default
  output:
    ansi:
      enabled: always
  http:
    converters:
      preferred-json-mapper: gson
logging:
  file: my.log
  path: ./logs/
---
spring:
  profiles: prod
  output:
    ansi:
      enabled: always
logging:
  file: my.log
  path: ./logs/
---
spring:
  profiles: dev
  output:
    ansi:
      enabled: always
logging:
  file: ./logs/my.log
  path: ./logs/
